image: r-base:3.5.1
variables:
  APT_PKGS: "libcurl4-openssl-dev libssh2-1-dev libssl-dev libxml2-dev zlib1g-dev git"

before_script:
- apt-get update
- apt-get install -y --no-install-recommends ${APT_PKGS}
- apt-get install -y --no-install-recommends qpdf pandoc pandoc-citeproc
- export PATH="/usr/local/lib/R/site-library/littler/examples/:${PATH}"
- echo "options(Ncpus = $(nproc --all))" >> /usr/local/lib/R/etc/Rprofile.site
- install2.r devtools
- r -e 'devtools::install_dev_deps()'

cache:
  key:${CI_COMMIT_REF_SLUG}
  paths:
  - /usr/local/lib/R/site-library/

stages:
- build
- test

build:
  stage: build
  script:
    - R CMD build .
test:
  stage: test
  script:
    - R -e 'source("https://bioconductor.org/biocLite.R"); biocLite(c("ggplot2", "flowCore", "flowClust", "openCyto", "ggcyto", "flowWorkspace", "scales", "Biobase"))'
    - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
    - R CMD check "${PKG_FILE_NAME}"
    - R -e 'devtools::test()'
