image: lmodolo/r_dev

stages:
- build
- check
- test

build:
  stage: build
  script:
    - R CMD build .

check:
  stage: check
  script:
    - R -e 'devtools::check()'

test:
  stage: test
  script:
    - R -e 'devtools::test()'
